### ISSUE TITLE
SASS lint config conflicts with prettier config

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/vets-website#13012]
`sass-lint.yml`
```yml
  quotes:
    - 1
    - style: double
```

`.prettierrc`
```json
  "singleQuote": true,
```

possible solutions:
1. change sass lint config
1. change prettier config
1. make prettier ignore sass files
