### ISSUE TITLE
Reconcile max-width of .row across repos

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2521]
## Problem

Inconsistent `max-width` values across repos create problems for keeping everything in sync. A mix of multiple definitions and high specificity selectors means that `.row` doesn't behave the same way everywhere.

## Selectors to refactor

_From `_va.scss`_

```scss
body .row.full {
  width: 100%;
  max-width: 100%;
}
```

```scss
.va-notice--banner {
  .row {
    max-width: 70em;
  }
}
```

_From `_hca.scss`_

```scss
body .row {
  max-width: 62.5em;
}
```

## Suggested fixes:

- [ ] Replace `body .row.full` selector with  `.va-row--full` selector.
- [ ] Modify markup of `include/header.html` so that  `.va-notice--banner .row` no longer exists.
- [ ] Change `body .row` to `.row`
