### ISSUE TITLE
Use heading styles consistently based on hierarchy within a page

### ISSUE THREAD

**Issue by crwallace** [department-of-veterans-affairs/vets-website#2675]
e.g. H1, H2, H3, etc.

@melwoodard -- Can you give a little more guidance on this or a style guide-type example of when certain headings should be used so we know which ones to switch.

**Comment by melwoodard** [comment]
There are 3 distinct steps needed here to get things normalized and up to speed:

- [ ] Make sure *all* heading elements use the same set of styles across vets.gov. There are conflicting font-size attributes for H3-H6 between the different apps. 

*Note: this should only apply to the core content area of a template. Things like list nav headings should stay as-is.*
- [ ] Once there is one global set of styles, modify H3-H6 styles according to the below CSS spec.
- [ ] Follow the mockup below demonstrating when and where certain headings should be used. 

The most common inconsistencies to look for are section headings on content pages like "How it Works", "See Also" and the sub-sections within them.

**Comment by melwoodard** [comment]
Make sure all H3-H5 elements use these styles across the board on vets.gov:

```css
    h3 {
      font-size: 1.8em;
      line-height: 1.5;
      font-weight: bold;
    }
    
    h4 {
      font-size: 1.35em;
      line-height: 1.5;
      font-weight: bold;
    }
    
    h5 {
      font-size: 1.15em;
      line-height: 1.5;
      font-weight: bold;
    }
    
    h6 {
      font-size: 1em;
      line-height: 1.5;
      font-weight: normal;
      text-transform: uppercase;
    }
```
